### ISSUE TITLE
Support Python 3.13 decompilation

### ISSUE THREAD

**Issue by greenozon** [zrax/pycdc#498]
# Tasks

- [ ] Bytecode support (pycdas)
- [ ] Handle new opcodes in AST builder
    - [ ] `BINARY_OP_INPLACE_ADD_UNICODE`
    - [ ] `EXIT_INIT_CHECK`
    - [ ] `FORMAT_SIMPLE`
    - [ ] `FORMAT_WITH_SPEC`
    - [ ] `TO_BOOL`
    - [ ] `UNPACK_SEQUENCE_LIST`
    - [ ] `UNPACK_SEQUENCE_TUPLE`
    - [ ] `UNPACK_SEQUENCE_TWO_TUPLE`
    - [ ] `CALL_KW`
    - [ ] `CONVERT_VALUE`
    - [ ] `ENTER_EXECUTOR`
    - [ ] `LOAD_FAST_LOAD_FAST`
    - [ ] `SET_FUNCTION_ATTRIBUTE`
    - [ ] `STORE_FAST_LOAD_FAST`
    - [ ] `STORE_FAST_STORE_FAST`
    - [ ] `BINARY_OP_ADD_FLOAT`
    - [ ] `BINARY_OP_ADD_INT`
    - [ ] `BINARY_OP_ADD_UNICODE`
    - [ ] `BINARY_OP_MULTIPLY_FLOAT`
    - [ ] `BINARY_OP_MULTIPLY_INT`
    - [ ] `BINARY_OP_SUBTRACT_FLOAT`
    - [ ] `BINARY_OP_SUBTRACT_INT`
    - [ ] `BINARY_SUBSCR_DICT`
    - [ ] `BINARY_SUBSCR_GETITEM`
    - [ ] `BINARY_SUBSCR_LIST_INT`
    - [ ] `BINARY_SUBSCR_STR_INT`
    - [ ] `BINARY_SUBSCR_TUPLE_INT`
    - [ ] `CALL_ALLOC_AND_ENTER_INIT`
    - [ ] `CALL_BOUND_METHOD_EXACT_ARGS`
    - [ ] `CALL_BOUND_METHOD_GENERAL`
    - [ ] `CALL_BUILTIN_CLASS`
    - [ ] `CALL_BUILTIN_FAST`
    - [ ] `CALL_BUILTIN_FAST_WITH_KEYWORDS`
    - [ ] `CALL_BUILTIN_O`
    - [ ] `CALL_ISINSTANCE`
    - [ ] `CALL_LEN`
    - [ ] `CALL_LIST_APPEND`
    - [ ] `CALL_METHOD_DESCRIPTOR_FAST`
    - [ ] `CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS`
    - [ ] `CALL_METHOD_DESCRIPTOR_NOARGS`
    - [ ] `CALL_METHOD_DESCRIPTOR_O`
    - [ ] `CALL_NON_PY_GENERAL`
    - [ ] `CALL_PY_EXACT_ARGS`
    - [ ] `CALL_PY_GENERAL`
    - [ ] `CALL_STR_1`
    - [ ] `CALL_TUPLE_1`
    - [ ] `CALL_TYPE_1`
    - [ ] `COMPARE_OP_FLOAT`
    - [ ] `COMPARE_OP_INT`
    - [ ] `COMPARE_OP_STR`
    - [ ] `CONTAINS_OP_DICT`
    - [ ] `CONTAINS_OP_SET`
    - [ ] `FOR_ITER_GEN`
    - [ ] `FOR_ITER_LIST`
    - [ ] `FOR_ITER_RANGE`
    - [ ] `FOR_ITER_TUPLE`
    - [ ] `LOAD_ATTR_CLASS`
    - [ ] `LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN`
    - [ ] `LOAD_ATTR_INSTANCE_VALUE`
    - [ ] `LOAD_ATTR_METHOD_LAZY_DICT`
    - [ ] `LOAD_ATTR_METHOD_NO_DICT`
    - [ ] `LOAD_ATTR_METHOD_WITH_VALUES`
    - [ ] `LOAD_ATTR_MODULE`
    - [ ] `LOAD_ATTR_NONDESCRIPTOR_NO_DICT`
    - [ ] `LOAD_ATTR_NONDESCRIPTOR_WITH_VALUES`
    - [ ] `LOAD_ATTR_PROPERTY`
    - [ ] `LOAD_ATTR_SLOT`
    - [ ] `LOAD_ATTR_WITH_HINT`
    - [ ] `LOAD_GLOBAL_BUILTIN`
    - [ ] `LOAD_GLOBAL_MODULE`
    - [ ] `LOAD_SUPER_ATTR_ATTR`
    - [ ] `LOAD_SUPER_ATTR_METHOD`
    - [ ] `RESUME_CHECK`
    - [ ] `SEND_GEN`
    - [ ] `STORE_ATTR_INSTANCE_VALUE`
    - [ ] `STORE_ATTR_SLOT`
    - [ ] `STORE_ATTR_WITH_HINT`
    - [ ] `STORE_SUBSCR_DICT`
    - [ ] `STORE_SUBSCR_LIST_INT`
    - [ ] `TO_BOOL_ALWAYS_TRUE`
    - [ ] `TO_BOOL_BOOL`
    - [ ] `TO_BOOL_INT`
    - [ ] `TO_BOOL_LIST`
    - [ ] `TO_BOOL_NONE`
    - [ ] `TO_BOOL_STR`
    - [ ] `UNPACK_SEQUENCE_LIST`
    - [ ] `UNPACK_SEQUENCE_TUPLE`
    - [ ] `UNPACK_SEQUENCE_TWO_TUPLE`
    - [ ] `INSTRUMENTED_CALL_KW`

**Comment by greenozon** [comment]
Initial support PR: https://github.com/zrax/pycdc/pull/497

**Comment by greenozon** [comment]
Last beta version of 3.13 was released today
3.13.0 beta 4: Thursday, 2024-07-18
no any changes in 3.13 opcodes

**Comment by greenozon** [comment]
Python 3.13 rc1 released
https://www.python.org/downloads/release/python-3130rc1/
